#pragma once
#ifndef _trading_ifc_src_trading_ifc_H_ThFjHTOiN8AHmo51sPeouKIqk6HDH8hQ_
#define _trading_ifc_src_trading_ifc_H_ThFjHTOiN8AHmo51sPeouKIqk6HDH8hQ_

namespace trading_ifc{

}

#endif /* _trading_ifc_src_trading_ifc_H_ThFjHTOiN8AHmo51sPeouKIqk6HDH8hQ_ */
